replicaCount: 1
image:
  repository: courtmate603fc8acr.azurecr.io/notification-service
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
resources: {}
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: "courtmate.duckdns.org"
  hosts:
    - paths:
        - path: /api/notifications(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: notification-service-tls
      hosts:
        - courtmate.duckdns.org
env:
  SUPABASE_URL: ""
  SUPABASE_KEY: ""
  SUPABASE_SERVICE_ROLE_KEY: ""
  SUPABASE_JWT_SECRET: ""
