replicaCount: 1
image:
  repository: courtmateacr.azurecr.io/notification-service
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8003
resources: {}
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - paths:
        - path: /api/notifications(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []
env:
  SUPABASE_URL: ""
  SUPABASE_KEY: ""
  SUPABASE_SERVICE_ROLE_KEY: ""
  SUPABASE_JWT_SECRET: ""
